apiVersion: apps/v1
kind: Deployment
metadata:
  name: "nginx"
  namespace: "nginx-namespace"
  labels:
    app: "nginx-app"
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1 
      maxSurge: 1  
  selector:
    matchLabels:
      app: "nginx-app"
  template:
    metadata:
      labels:
        app: "nginx-app"
    spec:
      imagePullSecrets:
        - name: your-image-pull-secret
      containers:
        - name: "nginx-app"
          image: nginx:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "1"
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 60
            timeoutSeconds: 5
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 2
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 60
            timeoutSeconds: 5
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 2
